### ISSUE TITLE
This needs to be updated upstream

### ISSUE THREAD

**Issue by Xtendera** [aseprite/libwebp#1]
Yeah.. It is current 1.2.1 and could be updated to 1.2.4.

**Comment by navidemad** [comment]
I'm using at the moment http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.3.0.tar.gz
But it will be great to bump it on the github too.
Thanks 👍🏻

**Comment by Xtendera** [comment]
Yeah it could be updated still... Doesn't seem like the developers are too quick to update (even my post was 7 months ago now).

**Comment by dacap** [comment]
Just in case, I'll push the new changes to this repository, anyway to update the Aseprite dependency we have to check first Skia (both the webp included in Skia and the one in Aseprite must match). So that's why we don't update some dependencies, it can bring a lot of compilation problems (mainly the ones included in Skia too).
